SELECT *
FROM (SELECT FOOD_TYPE,REST_ID,REST_NAME,FAVORITES
      FROM REST_INFO
      ORDER BY FAVORITES DESC
      LIMIT 20000) SUB
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC

# SELECT *
# FROM (SELECT FOOD_TYPE,REST_ID,REST_NAME,FAVORITES
#      FROM REST_INFO
#      ORDER BY FAVORITES DESC
#      LIMIT 112345) SUB
# GROUP BY FOOD_TYPE
# ORDER BY FOOD_TYPE DESC